### PR TITLE
Dbl prec history

### PR DESCRIPTION
**Pull request by jedwards4b**
Provides support for double precision IO in the cice history file.   Default is single precision,
but double precision is set for all testing.   Tested with single and double precision using 
ERI.f09_g17.DTEST.cheyenne_intel.cice-default
and PET_Ln3.f45_g37.DTEST.cheyenne_intel.cice-step
and both PIO_VERSION=1 and PIO_VERSION=2
This also fixes the issue of fill pattern differences between otherwise identical run and thus the issue of INFO_DBUG giving different results with different pe layouts.

### CODE REVIEW

**Review by dabail10 — APPROVED** [review]
I think this looks good. My baseline compares fail for cice-default tests because of the precision change. Also, the namelist compares all fail because of the new namelist parameter history_precision. The additional changes to fix the coupler FillValue comparison does not fix the cprnc check picking up FillValue differences.

**Comment by jedwards4b** [comment]
> The additional changes to fix the coupler FillValue comparison does not fix the cprnc check picking up FillValue differences.

In what test do you still see a failure?

**Comment by dabail10** [comment]
The failed test is here:

/glade2/scratch2/dbailey/ERP.f19_g17_rx1.DTEST.cheyenne_intel.cice-default.C.20180130_125134_w2vkrj

Is there a CIME tag to go with this?

**Comment by jedwards4b** [comment]
No CIME tag - I'll have a look at that test.

**Pull request merged**
