### PR TITLE
one more fill value fix

### PR DESCRIPTION
**Pull request by jedwards4b**
Add a fill value attribute for the cice restart file.

### CODE REVIEW

**Review by dabail10 — COMMENTED** [review]
I don't believe we want to label 0 as FillValue in the restart.

**Comment by jedwards4b** [comment]
In that case you need to not use it.  
https://github.com/ESCOMP/CESM_CICE5/blob/master/src/io_pio/ice_restart.F90#L548

**Comment by dabail10** [comment]
So, this is a bit of a catch 22. We want PIO to fill in the missing land blocks with "fillvalue" of 0, but we don't necessarily want the global attribute of "FillValue" to be 0. Does that make sense?

**Comment by jedwards4b** [comment]
You can't have your cake and eat it too - the fillvalue used in the call to write_darray must match the fill value defined for the field.

**Pull request closed without merging**
